# Context-aware content is drawn from this fixed, developer-authored
# vocabulary rather than generated by a live model. Two reasons: it keeps
# the feature genuinely free (no LLM API key/cost), and it keeps the
# text-to-speech step safe — flashcards.views.flashcard_audio already only
# ever speaks pre-written text for exactly this reason, and this reuses the
# same rule so a routine title a child types can never end up spoken back
# verbatim.
#
# Nepali text uses the casual "timi" imperative (e.g. "माझ", not the formal
# "माझ्नुहोस्") — the everyday register a parent actually speaks to a child
# in, not written/formal Nepali. `ne`/`en` are the short action word spoken
# as audio; `desc_ne`/`desc_en` are a one-line description of the action
# shown as supporting text on the card (not spoken).
#
# Each step has a stable `id` used both as a dict key for audio generation
# and as a React key on the frontend.

ROUTINE_STEP_SEQUENCES = [
    {
        'keywords': ['wake', 'get up', 'उठ', 'बिउँझ'],
        'sequence': [
            {'id': 'wake_make_bed', 'ne': 'ओछ्यान मिला', 'en': 'Make your bed', 'icon': '🛏️',
             'desc_ne': 'बिहान उठेपछि सबैभन्दा पहिले ओछ्यानको तन्ना र सिरानी मिलाऊ',
             'desc_en': 'Right after waking up, straighten your blanket and pillow neatly'},
            {'id': 'wake_brush', 'ne': 'दाँत माझ', 'en': 'Brush your teeth', 'icon': '🪥',
             'desc_ne': 'ब्रशमा टुथपेस्ट लगाएर दाँत राम्ररी माझ',
             'desc_en': 'Put toothpaste on your brush and scrub your teeth well'},
            {'id': 'wake_wash_face', 'ne': 'अनुहार धो', 'en': 'Wash your face', 'icon': '🧼',
             'desc_ne': 'चिसो पानीले अनुहार राम्ररी धो',
             'desc_en': 'Splash some water and wash your whole face'},
            {'id': 'wake_dress', 'ne': 'लुगा लगा', 'en': 'Get dressed', 'icon': '👕',
             'desc_ne': 'आजको लागि सफा लुगा छानेर लगा',
             'desc_en': 'Pick clean clothes for today and put them on'},
            {'id': 'wake_breakfast', 'ne': 'नास्ता खाऊ', 'en': 'Eat breakfast', 'icon': '🥣',
             'desc_ne': 'टेबलमा बसेर नास्ता बिस्तारै खाऊ',
             'desc_en': 'Sit at the table and eat your breakfast slowly'},
        ],
    },
    {
        'keywords': ['teeth', 'brush', 'दाँत', 'माझ्'],
        'sequence': [
            {'id': 'brush_wet', 'ne': 'ब्रश भिजाऊ', 'en': 'Wet your brush', 'icon': '🚿',
             'desc_ne': 'ब्रशलाई पानीमुनि राखेर भिजाऊ',
             'desc_en': 'Hold your brush under running water to wet it'},
            {'id': 'brush_paste', 'ne': 'टुथपेस्ट लगा', 'en': 'Add toothpaste', 'icon': '🧴',
             'desc_ne': 'ब्रशमा मटरदाना जत्रो टुथपेस्ट लगा',
             'desc_en': 'Squeeze a pea-sized bit of toothpaste onto the brush'},
            {'id': 'brush_teeth_step', 'ne': 'दाँत माझ', 'en': 'Brush all your teeth', 'icon': '🪥',
             'desc_ne': 'अगाडि, पछाडि र माथि-तल सबै दाँत माझ',
             'desc_en': 'Brush the front, back, and top of every tooth'},
            {'id': 'brush_rinse', 'ne': 'मुख कुल्ला गर', 'en': 'Rinse your mouth', 'icon': '💧',
             'desc_ne': 'मुखमा पानी हालेर कुल्ला गर र थुक',
             'desc_en': 'Swish water around your mouth and spit it out'},
        ],
    },
    {
        'keywords': ['breakfast', 'नास्ता', 'खाजा', 'बिहान'],
        'sequence': [
            {'id': 'meal_wash_hands', 'ne': 'हात धो', 'en': 'Wash your hands', 'icon': '🧼',
             'desc_ne': 'साबुन लगाएर दुवै हात राम्ररी धो',
             'desc_en': 'Use soap and wash both your hands well'},
            {'id': 'meal_sit', 'ne': 'टेबलमा बस', 'en': 'Sit at the table', 'icon': '🪑',
             'desc_ne': 'खाना खान टेबलको आफ्नो सिटमा बस',
             'desc_en': 'Sit down at your seat at the table to eat'},
            {'id': 'meal_eat', 'ne': 'बिस्तारै खाऊ', 'en': 'Eat slowly', 'icon': '🥣',
             'desc_ne': 'एक-एक गाँस बिस्तारै चपाएर खाऊ',
             'desc_en': 'Take small bites and chew slowly'},
            {'id': 'meal_clear', 'ne': 'भाँडा राख', 'en': 'Put your plate away', 'icon': '🍽️',
             'desc_ne': 'खाइसकेपछि आफ्नो भाँडा राख',
             'desc_en': "Once you're done, put your own plate away"},
        ],
    },
    {
        'keywords': ['lunch', 'दिउँसो'],
        'sequence': [
            {'id': 'lunch_wash_hands', 'ne': 'हात धो', 'en': 'Wash your hands', 'icon': '🧼',
             'desc_ne': 'खाना अघि साबुन लगाएर हात धो',
             'desc_en': 'Wash your hands with soap before eating'},
            {'id': 'lunch_sit', 'ne': 'टेबलमा बस', 'en': 'Sit at the table', 'icon': '🪑',
             'desc_ne': 'दिउँसोको खानाको लागि टेबलमा बस',
             'desc_en': 'Sit at the table for lunch'},
            {'id': 'lunch_eat', 'ne': 'खाना खाऊ', 'en': 'Eat your lunch', 'icon': '🍱',
             'desc_ne': 'थालमा भएको सबै खाना खाऊ',
             'desc_en': 'Eat all the food on your plate'},
            {'id': 'lunch_clear', 'ne': 'भाँडा राख', 'en': 'Put your plate away', 'icon': '🍽️',
             'desc_ne': 'खाइसकेपछि भाँडा राखिदेऊ',
             'desc_en': "Put your plate away when you're finished"},
        ],
    },
    {
        'keywords': ['dinner', 'साँझ', 'रात'],
        'sequence': [
            {'id': 'dinner_wash_hands', 'ne': 'हात धो', 'en': 'Wash your hands', 'icon': '🧼',
             'desc_ne': 'खाना अघि हात धो',
             'desc_en': 'Wash your hands before dinner'},
            {'id': 'dinner_sit', 'ne': 'टेबलमा बस', 'en': 'Sit at the table', 'icon': '🪑',
             'desc_ne': 'साँझको खानाको लागि टेबलमा बस',
             'desc_en': 'Sit at the table for dinner'},
            {'id': 'dinner_eat', 'ne': 'खाना खाऊ', 'en': 'Eat your dinner', 'icon': '🍽️',
             'desc_ne': 'परिवारसँगै बसेर खाना खाऊ',
             'desc_en': 'Eat your dinner together with family'},
            {'id': 'dinner_teeth', 'ne': 'दाँत माझ', 'en': 'Brush your teeth', 'icon': '🪥',
             'desc_ne': 'सुत्नुअघि दाँत माझ',
             'desc_en': 'Brush your teeth before you sleep'},
        ],
    },
    {
        'keywords': ['bath', 'shower', 'नुहाउ'],
        'sequence': [
            {'id': 'bath_undress', 'ne': 'लुगा फुकाल', 'en': 'Take off your clothes', 'icon': '👕',
             'desc_ne': 'नुहाउनुअघि लगाएका लुगा फुकाल',
             'desc_en': 'Take off your clothes before you bathe'},
            {'id': 'bath_wash', 'ne': 'जिउ धो', 'en': 'Wash your body', 'icon': '🛁',
             'desc_ne': 'साबुन लगाएर जिउ राम्ररी धो',
             'desc_en': 'Use soap and wash your whole body'},
            {'id': 'bath_hair', 'ne': 'कपाल धो', 'en': 'Wash your hair', 'icon': '🧴',
             'desc_ne': 'शैम्पू लगाएर कपाल धो',
             'desc_en': 'Use shampoo and wash your hair'},
            {'id': 'bath_dry', 'ne': 'टावलले पुछ', 'en': 'Dry yourself with a towel', 'icon': '🧻',
             'desc_ne': 'नुहाइसकेपछि टावलले जिउ पुछ',
             'desc_en': 'Dry your whole body with a towel after'},
            {'id': 'bath_dress', 'ne': 'सफा लुगा लगा', 'en': 'Put on clean clothes', 'icon': '👚',
             'desc_ne': 'सुकेपछि सफा लुगा लगा',
             'desc_en': "Once you're dry, put on clean clothes"},
        ],
    },
    {
        'keywords': ['study', 'homework', 'पढ', 'school', 'विद्यालय'],
        'sequence': [
            {'id': 'study_bag', 'ne': 'झोला मिला', 'en': 'Get your bag ready', 'icon': '🎒',
             'desc_ne': 'भोलिको लागि किताब-कापी झोलामा मिला',
             'desc_en': 'Pack your books and copies into your bag'},
            {'id': 'study_sit', 'ne': 'डेस्कमा बस', 'en': 'Sit at your desk', 'icon': '📖',
             'desc_ne': 'पढ्ने ठाउँमा शान्तसँग बस',
             'desc_en': 'Sit down quietly at your study spot'},
            {'id': 'study_books', 'ne': 'किताब खोल', 'en': 'Open your books', 'icon': '📚',
             'desc_ne': 'आजको पाठ भएको किताब खोल',
             'desc_en': "Open the book for today's lesson"},
            {'id': 'study_write', 'ne': 'काम गर', 'en': 'Do your work', 'icon': '✏️',
             'desc_ne': 'गृहकार्य वा अभ्यास ध्यान दिएर गर',
             'desc_en': 'Do your homework or practice carefully'},
        ],
    },
    {
        'keywords': ['sleep', 'bed', 'nap', 'सुत', 'निद्रा'],
        'sequence': [
            {'id': 'sleep_teeth', 'ne': 'दाँत माझ', 'en': 'Brush your teeth', 'icon': '🪥',
             'desc_ne': 'सुत्नुअघि दाँत माझ',
             'desc_en': 'Brush your teeth before bedtime'},
            {'id': 'sleep_pajamas', 'ne': 'सुत्ने लुगा लगा', 'en': 'Put on pajamas', 'icon': '🩳',
             'desc_ne': 'सुत्ने आरामदायी लुगा लगा',
             'desc_en': 'Change into comfy pajamas for bed'},
            {'id': 'sleep_lights', 'ne': 'बत्ती निभा', 'en': 'Turn off the lights', 'icon': '💡',
             'desc_ne': 'कोठाको बत्ती निभाएर अध्यारो पार',
             'desc_en': 'Turn off the lights to make it dark'},
            {'id': 'sleep_bed', 'ne': 'ओछ्यानमा जाऊ', 'en': 'Go to bed', 'icon': '🌙',
             'desc_ne': 'ओछ्यानमा गएर आँखा चिम्ल',
             'desc_en': 'Get into bed and close your eyes'},
        ],
    },
]

# Shown when the current routine item's title doesn't match any of the
# sequences above, so there is still something contextual on screen.
DEFAULT_ROUTINE_SEQUENCE = [
    {'id': 'default_ready', 'ne': 'तयार होऊ', 'en': 'Get ready', 'icon': '⏰',
     'desc_ne': 'यो कामको लागि आफूलाई तयार पार',
     'desc_en': 'Get yourself ready for this activity'},
    {'id': 'default_focus', 'ne': 'ध्यान देऊ', 'en': 'Pay attention', 'icon': '🙂',
     'desc_ne': 'जे गर्दैछौ त्यसमा ध्यान देऊ',
     'desc_en': "Pay close attention to what you're doing"},
    {'id': 'default_done', 'ne': 'सिध्याऊ', 'en': 'Finish it up', 'icon': '✅',
     'desc_ne': 'सुरु गरेको काम पूरा गरेर सिध्याऊ',
     'desc_en': "Finish up whatever you've started"},
]

# Keyed by the place_category dashboard.views.PLACE_CATEGORY_MAP resolves
# GPS coordinates into.
LOCATION_STEP_SEQUENCES = {
    'restaurant': [
        {'id': 'restaurant_sit', 'ne': 'बस', 'en': 'Sit down', 'icon': '🪑',
         'desc_ne': 'टेबलमा गएर आराम सँग बस',
         'desc_en': 'Go to the table and sit down comfortably'},
        {'id': 'restaurant_order', 'ne': 'खाना अर्डर गर', 'en': 'Order food', 'icon': '📋',
         'desc_ne': 'के खाने हो भनेर अर्डर गर',
         'desc_en': "Tell them what food you'd like to order"},
        {'id': 'restaurant_wait', 'ne': 'पर्ख', 'en': 'Wait patiently', 'icon': '⏳',
         'desc_ne': 'खाना आउँदासम्म शान्तसँग पर्ख',
         'desc_en': 'Wait quietly until your food arrives'},
        {'id': 'restaurant_spoon', 'ne': 'चम्चाले खाऊ', 'en': 'Use your spoon', 'icon': '🥄',
         'desc_ne': 'चम्चा समातेर बिस्तारै खाऊ',
         'desc_en': 'Hold your spoon and eat slowly'},
        {'id': 'restaurant_eat', 'ne': 'खाऊ', 'en': 'Eat your food', 'icon': '🍽️',
         'desc_ne': 'आफ्नो थालको खाना खाऊ',
         'desc_en': 'Eat the food from your own plate'},
        {'id': 'restaurant_thanks', 'ne': 'धन्यवाद भन', 'en': 'Say thank you', 'icon': '🙏',
         'desc_ne': 'खाना ल्याइदिँदा धन्यवाद भन',
         'desc_en': 'Say thank you when they bring your food'},
    ],
    'school': [
        {'id': 'school_hello', 'ne': 'नमस्ते भन', 'en': 'Say hello', 'icon': '👋',
         'desc_ne': 'शिक्षक र साथीलाई नमस्ते भन',
         'desc_en': 'Say hello to your teacher and friends'},
        {'id': 'school_sit', 'ne': 'सिटमा बस', 'en': 'Sit at your seat', 'icon': '🪑',
         'desc_ne': 'आफ्नो सिटमा गएर बस',
         'desc_en': 'Go to your own seat and sit down'},
        {'id': 'school_listen', 'ne': 'ध्यान दिएर सुन', 'en': 'Listen carefully', 'icon': '👂',
         'desc_ne': 'शिक्षकले भनेको कुरा ध्यान दिएर सुन',
         'desc_en': 'Listen carefully to what your teacher says'},
        {'id': 'school_raise_hand', 'ne': 'हात उठा', 'en': 'Raise your hand', 'icon': '✋',
         'desc_ne': 'सोध्न मन लागे हात उठा',
         'desc_en': 'Raise your hand if you want to ask something'},
    ],
    'park': [
        {'id': 'park_walk', 'ne': 'हिँड', 'en': 'Walk around', 'icon': '🚶',
         'desc_ne': 'वरिपरि हिँडेर हेर',
         'desc_en': 'Walk around and look at the park'},
        {'id': 'park_play', 'ne': 'खेल', 'en': 'Play safely', 'icon': '⚽',
         'desc_ne': 'साथीहरूसँग मिलेर खेल',
         'desc_en': 'Play together nicely with your friends'},
        {'id': 'park_swing', 'ne': 'झुलामा झुल', 'en': 'Try the swing', 'icon': '🎠',
         'desc_ne': 'सावधानीसाथ झुलामा गएर झुल',
         'desc_en': 'Carefully get on the swing and swing'},
        {'id': 'park_water', 'ne': 'पानी खाऊ', 'en': 'Drink some water', 'icon': '💧',
         'desc_ne': 'थाकेको महसुस भए पानी खाऊ',
         'desc_en': 'If you feel tired, drink some water'},
    ],
    'hospital': [
        {'id': 'hospital_calm', 'ne': 'शान्त होऊ', 'en': 'Stay calm', 'icon': '🙂',
         'desc_ne': 'डराउनु पर्दैन, शान्त होऊ',
         'desc_en': "There's nothing to be afraid of, stay calm"},
        {'id': 'hospital_sit', 'ne': 'बसेर पर्ख', 'en': 'Sit and wait', 'icon': '🪑',
         'desc_ne': 'आफ्नो पालो नआउञ्जेल बसेर पर्ख',
         'desc_en': "Sit and wait until it's your turn"},
        {'id': 'hospital_tell', 'ne': 'डाक्टरलाई भन', 'en': 'Tell the doctor how you feel', 'icon': '🩺',
         'desc_ne': 'कहाँ दुख्छ भनेर डाक्टरलाई भन',
         'desc_en': 'Tell the doctor where it hurts'},
        {'id': 'hospital_medicine', 'ne': 'औषधि खाऊ', 'en': 'Take your medicine', 'icon': '💊',
         'desc_ne': 'डाक्टरले दिएको औषधि खाऊ',
         'desc_en': 'Take the medicine the doctor gave you'},
    ],
    'store': [
        {'id': 'store_pick', 'ne': 'सामान छान', 'en': 'Pick what you need', 'icon': '🛒',
         'desc_ne': 'चाहिने सामान छानेर टोकरीमा राख',
         'desc_en': 'Pick what you need and put it in the basket'},
        {'id': 'store_counter', 'ne': 'काउन्टरमा जाऊ', 'en': 'Go to the counter', 'icon': '🧾',
         'desc_ne': 'सामान लिएर काउन्टरमा जाऊ',
         'desc_en': 'Take your items to the counter'},
        {'id': 'store_pay', 'ne': 'पैसा तिर', 'en': 'Pay the money', 'icon': '💵',
         'desc_ne': 'सामानको पैसा तिर',
         'desc_en': 'Pay the money for what you bought'},
        {'id': 'store_thanks', 'ne': 'धन्यवाद भन', 'en': 'Say thank you', 'icon': '🙏',
         'desc_ne': 'सामान लिएपछि धन्यवाद भन',
         'desc_en': 'Say thank you after you get your things'},
    ],
    'home': [
        {'id': 'home_shoes', 'ne': 'जुत्ता फुकाल', 'en': 'Take off your shoes', 'icon': '👟',
         'desc_ne': 'घर भित्र पस्नुअघि जुत्ता फुकाल',
         'desc_en': 'Take off your shoes before going inside'},
        {'id': 'home_wash', 'ne': 'हात धो', 'en': 'Wash your hands', 'icon': '🧼',
         'desc_ne': 'बाहिरबाट आएपछि हात धो',
         'desc_en': 'Wash your hands after coming from outside'},
        {'id': 'home_relax', 'ne': 'आराम गर', 'en': 'Relax at home', 'icon': '🏠',
         'desc_ne': 'घरमा आराम गरेर बस',
         'desc_en': "Relax and rest now that you're home"},
    ],
}


def match_routine_sequence(title):
    lower = (title or '').lower()
    for rule in ROUTINE_STEP_SEQUENCES:
        if any(keyword.lower() in lower for keyword in rule['keywords']):
            return rule['sequence']
    return None
